### ISSUE TITLE
LinkStack has problems with links as soon as 'custom locations' are specified in the NGINX reverse proxy

### ISSUE THREAD

**Issue by NoFloXx** [LinkStackOrg/linkstack-docker#102]
In my home, LinkStack is on Proxmox and is served by the NGINX reverse proxy, which actually works.
However, LinkStack becomes obstructive as soon as you click on the links. Then I get a 404 error when I set up the setup in NGINX like in this screenshot here:
https://abload.de/img/capture_002_16112023_z0c95.jpg

Everything works correctly if I set it up like this:
https://abload.de/img/capture_001_16112023_gkixt.jpg

That would be fine in itself, but what bothers me is that with the version that works, there is a '/@NoFloXx' next to the address in the browser and that's not the case with the 404 error when setting it up, but the links don't work either and that makes no sense.

You can test it yourself like this:
https://www.nofloxx.de/ (everything works like this, but with /@NoFloXx in the browser)
https://nofloxx.de/ (I would like it that way, but links don't work).

Do you have any idea what else I can do?

###

Bei mir liegt LinkStack zu Hause aufm Proxmox und wird vom NGINX-Reverseproxy bedient, was auch an sich funktioniert.
Jedoch stellt sich LinkStack quer, sobald man auf die Links klickt. Da kommt dann ein 404-Fehler, wenn ich die Einrichtung im NGINX so einrichte, wie auf diesem Screenshot hier:
https://abload.de/img/capture_002_16112023_z0c95.jpg

Korrekt funktioniert alles, wenn ich es so einrichte:
https://abload.de/img/capture_001_16112023_gkixt.jpg

Wäre ja an sich in Ordnung, mich stört aber, dass bei der funktionierenden Variante dann im Browser neben der Adresse dann ein '/@NoFloXx' steht und das ist bei der Einrichtung mit dem 404-Fehler nicht, die Links gehen dann aber auch nicht und das ist ja dann auch sinnfrei.

Testen könnt ihr das selber so:
https://www.nofloxx.de/ ( so klappt alles, aber mit dem /@NoFloXx im Browser )
https://nofloxx.de/ ( so hätte ich es gerne, aber Links gehen nicht ).

Habt ihr da eine Idee, was ich noch machen kann?

**Comment by NoFloXx** [comment]
No, I wasn't aware of that.
But since I host LinkStack locally at my home and don't have IPv4, I have to do this via Nginx.
How do I configure Nginx in LinkStack?
Maybe that already solves my problem?

**Comment by JulianPrieber** [comment]
I use NGINX for every LinkStack instance I host. If you want your user profile to be your home page, you can set it up easily using LinkStack's internal routing system. Just go to your configuration settings and choose your profile under the "Set user page as Home Page" option.

**Comment by NoFloXx** [comment]
Ah okay. I didn't see this option.
But unfortunately that doesn't work for me because I have 3 accounts running on my installation of LinkStack.
Can this be solved another way? Because that bothers me a lot and I don't want to have 3 separate instances running on my Proxmox server for LinkStack, since each instance requires more RAM etc....

**Comment by JulianPrieber** [comment]
This only works for one user

**Comment by NoFloXx** [comment]
Thanks, I've now solved it the way you did:
A new instance was opened in Proxmox for each user. It's a shame that this can't be solved any other way.

But I still thank you for your help! <3

**Comment by JulianPrieber** [comment]
I'm not saying it's impossible using NGINX, just with the setting in the app.  I'm pretty sure this can be done, especially with simple redirects. Using NGINX should help you achieve it, though I'm not entirely sure if I can assist you directly. Still, it should definitely work.

**Comment by NoFloXx** [comment]
Yes, I have already tried several or 2 variants in NGINX and neither of them worked.
Once under Locations I specified the IP/@User and once just IP and then this in the field for other configurations at the bottom:
location = / {
  return 301 /@User;
}
That didn't work either.

So thank you, at least that's how it works. :)

**Comment by JulianPrieber** [comment]
Doing the redirect is easy. Just add the domains you want to redirect to your block.
Then add this somewhere to your block:

  if ($host = 'exmaple.com') {
    return 301 https://xyz.com/@admin;
  }

**Comment by NoFloXx** [comment]
That works, but what bothers me about this 'redirection' is that the browser then says /USER next to the address and I don't want that.
That's why I'm leaving it this way now so that I use one instance for each user. Not so wild. :)

**Comment by JulianPrieber** [comment]
@NoFloXx This is now a full feature: https://github.com/LinkStackOrg/LinkStack/releases/tag/v4.6.0#3

**Comment by NoFloXx** [comment]
@JulianPrieber
Thank you for that info!
But how do I put that into the config and where?
Unfortunately this doesn't work in the NGINX reverse proxy...
Sorry, I'm not a programmer or IT person, I just do this as a hobby.

**Comment by JulianPrieber** [comment]
You just paste the example into your advanced config somewhere after the `return [`. If you want to make sure it's not going to cause any errors, you can validate your config before saving with this site: https://phpcodechecker.com/.

I assure you this works on NGINX. All our features are tested and working on NGINX and Apache. The example shown in the release notes is running on NGINX.

Everyone working on this project is doing this as a hobby, we're all just learning as we go.

**Comment by JulianPrieber** [comment]
I made some changes to the Advanced Config: https://github.com/LinkStackOrg/LinkStack/blob/main/storage/templates/advanced-config.php

This should make it a bit more clear where you can add this option.

**Comment by NoFloXx** [comment]
Perfect, I've now managed it using the ID function.
I thank you!! <3
