### ISSUE TITLE
Multiple Pages Per User [Feature Request]

### ISSUE THREAD

**Issue by wwboynton** [LinkStackOrg/linkstack-docker#105]
It's totally feasible that a user might want to maintain multiple different link pages. Perhaps the same person has a personal link page and also maintains one for a book club they host at their home, or something like that. It seems like right now, the whole system is predicated on one page per user, and the only way to create multiple pages is to register multiple accounts. That seems unwieldy and it would be really neat if it were a one-to-many relationship.

Thanks for the excellent work! This is a tremendous fork with a lot of polish on it.

**Comment by JulianPrieber** [comment]
Already wokring on it.
