### ISSUE TITLE
SSL Certificates

### ISSUE THREAD

**Issue by Chase295** [LinkStackOrg/linkstack-docker#109]
Hello Guys,

I can´t find the SSL certificate at /etc/ssl/... for the Linkstack website. Did anyone knows how I can change now the certificat? I didn´t find any infomartions in the Internet.

Thank you verry much

**Comment by lastsamurai26** [comment]
![image](https://github.com/LinkStackOrg/linkstack-docker/assets/3257844/6ce4e7ca-ba4b-4c9d-9b87-59d75780813a)

Here are the certs if you can't find the folder you need to create it
