### ISSUE TITLE
[Sun Jan 07 13:43:21.961240 2024] [httpd.conf] ::1 - - "GET / HTTP/1.0" 400 450 "-" "-"

### ISSUE THREAD

**Issue by hrqmonteiro** [LinkStackOrg/linkstack-docker#111]
![image](https://github.com/LinkStackOrg/linkstack-docker/assets/17055027/41cce001-9eef-4f78-86a7-2b5650d894a9)

![image](https://github.com/LinkStackOrg/linkstack-docker/assets/17055027/8e3470a8-4377-407d-8231-b8c9441adc54)

```
[Sun Jan 07 13:43:33.859225 2024] [httpd.conf] ::1 - - "GET / HTTP/1.0" 400 450 "-" "-"
```

**Comment by lastsamurai26** [comment]
https://github.com/LinkStackOrg/linkstack-docker/issues/113
