### ISSUE TITLE
cant deploy

### ISSUE THREAD

**Issue by wildmarkos** [LinkStackOrg/linkstack-docker#113]
seems that there is an apache error when trying to deploy that ends giving error 400 in a fresh deployment... can you help me to deploy it in Render.com for example?

**Comment by lastsamurai26** [comment]
Can you show us your docker compose. Iff you using your own folder and not the docker volume please fill the folder on your own and set inside of the container apache:apache to the folders

**Comment by wildmarkos** [comment]
trying to deploy via:
https://hub.docker.com/r/linkstackorg/linkstack

it is using:
https://github.com/LinkStackOrg/linkstack-docker/blob/main/docker-compose.yml

also tested with some changes in docker-compose.yml via fork, with not success.
here: https://github.com/wildmarkos/linkstack-docker/blob/main/docker-compose.yml


investigating seems that could be that free accs doesnt have storage in Render.com(?)

**Comment by wildmarkos** [comment]
Seems that is the same issue #111

**Comment by lastsamurai26** [comment]
ok
if you are using this 
    volumes:
      - /opt/containers/ls/httpdocs:/htdocs

    then you need to fill the Folder on your own 

if you using this 
    volumes:
      - ls_data:/htdocs

and at the End of the file 

volumes:
  ls_data:
the it works without filling

**Comment by wildmarkos** [comment]
updated like this:
https://github.com/wildmarkos/linkstack-docker/blob/main/docker-compose.yml

but seems that is problem that the free version of render doesnt support mount storage, can it be the problem? is there a workaround to deplot it without storage?

**Comment by lastsamurai26** [comment]
`version: '3'
services:
  linkstack:
    container_name: linkstack
    image: linkstackorg/linkstack
    environment:
      - HTTP_SERVER_NAME="domain.me" 
      - HTTPS_SERVER_NAME="domain.me"
      - SERVER_ADMIN="admin@example.xyz"
      - TZ="Europe/Berlin"
      - PHP_MEMORY_LIMIT="512M"
      - UPLOAD_MAX_FILESIZE="8M"
    restart: always
    volumes:
      - /opt/containers/ls_data/httpdocs:/htdocs
      - /opt/containers/ls_data/ssl_apache:/etc/ssl/apache2
    networks:
      - traefik_web
networks:
  traefik_web:
   external: true`

this is my compose and it works, the only things is you need to fill the folder by yourself ;)

**Comment by saschabrockel** [comment]
I don't get why it has to be added manually. I mean every Docker service I know just works without an extra specified volume. And where do I get the files that belong to `/htdocs`?

For me, it was even worse. I had set up everything. I restarted Docker and realized everything was gone. Then I goddamn realized that there was nothing saved in the folder. I still don't know how it even used to work and saved my changes.

**Comment by lastsamurai26** [comment]
you need to unzip the download https://github.com/linkstackorg/linkstack/releases/latest/download/linkstack.zip into the /htdocs folder an in side of the docker you need to ues chwon -R apache:apache /htdocs 

Unraid is maintaned by one of our community

**Comment by saschabrockel** [comment]
@lastsamurai26 thank you but where is the difference in the unRAID package?
