### ISSUE TITLE
Update image

### ISSUE THREAD

**Issue by kimtiago** [LinkStackOrg/linkstack-docker#114]
Hi,

Why the image isn't updated? It is still 4.2.3

**Comment by SpecialAro** [comment]
Hi @JulianPrieber, I was about to file an issue saying that dockerhub images are not up to date with the latest linkstack when I saw this issue.

I think that @kimtiago was referring to this and not to the "self-updater" inside linkstack.

Would you be able to trigger a build action to build a docker image with the latest linkstack and push it to dockerhub?

Thank you so much in advance! Let me know if I can help in any way.
