### ISSUE TITLE
i want to add a web sdk to my linkstack page, how should i do it, which file should i add

### ISSUE THREAD

**Issue by xyychenchen** [LinkStackOrg/linkstack-docker#119]

**Comment by JulianPrieber** [comment]
Please see: https://github.com/LinkStackOrg/LinkStack

**Comment by xyychenchen** [comment]
> Please see: https://github.com/LinkStackOrg/LinkStack

thanks for your reply, whichi file should i insert my web sdk in , would you plz tell me thank you so much !

**Comment by JulianPrieber** [comment]
Maybe look in the views/linkstack folder?
I'm not exactly sure what you're trying to do.

**Comment by xyychenchen** [comment]
> Maybe look in the views/linkstack folder?
> I'm not exactly sure what you're trying to do.

yeap, that's the one, thanks so much
