### ISSUE TITLE
I cant run container console

### ISSUE THREAD

**Issue by jflorido94** [LinkStackOrg/linkstack-docker#120]
![image](https://github.com/LinkStackOrg/linkstack-docker/assets/58602366/89c48fed-d630-4f51-ac00-d0aa3f92c116)

Im using portainer and I cant open the console.

I get the error "Unable to retrieve image details"

Hope have some answer

**Comment by lastsamurai26** [comment]
bash or sh ? 
try sh

**Comment by jflorido94** [comment]
Hi, ty for answer.

Said it just when I click on console. Dont time to choose bash or sh

________________________________
De: Frank ***@***.***>
Enviado: martes, 4 de junio de 2024 12:59
Para: LinkStackOrg/linkstack-docker ***@***.***>
Cc: Javier Florido Pavon ***@***.***>; Author ***@***.***>
Asunto: Re: [LinkStackOrg/linkstack-docker] I cant run container console (Issue #120)


bash or sh ?
try sh

**Comment by lastsamurai26** [comment]
![image](https://github.com/LinkStackOrg/linkstack-docker/assets/3257844/6808f9a1-1167-4504-bac8-a36a950332c4)

normally bash works but for linkstack we only allow sh
