### ISSUE TITLE
Cannot get favicon.ico from a specific site

### ISSUE THREAD

**Issue by roughnecks** [LinkStackOrg/linkstack-docker#121]
Hello,

I just set up my own Linkstack docker instance and it's working fine but I cannot get the favicon from "https://woodpeckersnest.space/" to show up in custom link; it is always displayed as a globe, no matter what I tried (refreshing cache, converting again to .ico with gimp and online converters..).

What could the cause be? What else should I try?

Thanks

**Comment by lastsamurai26** [comment]
the Problem is there are no favicons in the root folder 

<link rel="icon" sizes="32x32" type="image/x-icon" href="images/favicon.ico">
<link rel="icon" sizes="any" type="image/svg+xml" href="images/favicon.svg">

this is the problem

**Comment by roughnecks** [comment]
Ah yes, sorry, I changed it recently while trying other configurations.
A favicon.ico has always been in the root when I tried, but I'm closing this anyway since I don't want it there anymore and I also unchecked the option to use favicons even for other custom links, so now they all have the same icon with the arrow.
