### ISSUE TITLE
Cannot run backup or auto-updater

### ISSUE THREAD

**Issue by Death-Pact** [LinkStackOrg/linkstack-docker#122]
Keep getting a same error on my docker container logs:

Fatal error: Maximum execution time of 30+2 seconds exceeded (terminated) in /htdocs/vendor/spatie/laravel-backup/src/Tasks/Backup/Zip.php on line 87

I am attempting to update from 4.2.3 -> 4.8.0

it leaves a temp folder in my /backup directory and yields a "500 | Server Error" message on my web browser.

Any idea why this happens?

**Comment by lastsamurai26** [comment]
PLease share your php.ini and your startcommand for the docker 

the default max_execution_time is 30 sec
you can change this in /etc/php82/php.ini

Your Syste, needs longer than 30 sec tu make a backup
