### ISSUE TITLE
Exitting with error code 137

### ISSUE THREAD

**Issue by voryzen** [LinkStackOrg/linkstack-docker#123]
Hi,

Linkstack repeatedly exiting with error code 137.

Been following the various issues, and the docs, but I'm stuck for what to do.

Happy to provide logs, as requested. Is there a known reason for this issue?

**Comment by lastsamurai26** [comment]
can you provide us a way to reproduce this ?

**Comment by voryzen** [comment]
Debian 12, Linux 6.10-25.
Docker 20.10.24, Docker compose 1.29.2
Traefik 2.11.10

I'll update with the compose file, when I get chance.
Is there anything else you'll need?

**Comment by voryzen** [comment]
I've moved on to a better product.
I'll review this product, according to my experience (or lack thereof) with the devs.
