### ISSUE TITLE
GUI automatic update 4.2.3 - 4.8.0 fails due to backup not completing

### ISSUE THREAD

**Issue by klinkeye** [LinkStackOrg/linkstack-docker#125]
When clicking automatic update, it first forces a backup, but it fails showing on screen:
![image](https://github.com/user-attachments/assets/daf1f2f4-7702-40ac-b33e-bd92e000dba9)

When I do a manual update to the docker volume, I get the empty "pre-defined site" list issue. Along with all sorts of permissions issues with the database or /htdocs/storage/logs/laravel.log (cannot append to log)

I've also tried to deploy with the /htdocs from the release package in a local folder and mapping that in my compose (still get the permission issues - either DB or laravel.log).

**Comment by JulianPrieber** [comment]
Disable backups when updating in your config.

**Comment by klinkeye** [comment]
This helped. Thank you. I missed the option in the settings to backup without update.
