### ISSUE TITLE
Unable to create links. 

### ISSUE THREAD

**Issue by wolfinside41** [LinkStackOrg/linkstack-docker#40]
Fresh install tonight. Just has an infinite loading circle.
![image](https://user-images.githubusercontent.com/14943964/211733514-eb488279-08a0-435c-b3c4-0294e8c6c052.png)
92.168.3.1 - - [11/Jan/2023:06:38:50 +0000] "GET /studio/js/jquery-block-ui.js HTTP/1.1" 304 - "http://172.20.69.53/studio/add-link" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.76"
192.168.3.1 - - [11/Jan/2023:06:38:50 +0000] "GET /studio/external-dependencies/fonts/bootstrap-icons.woff2?524846017b983fc8ded9325d94ed40f3 HTTP/1.1" 304 -
192.168.3.1 - - [11/Jan/2023:06:38:50 +0000] "GET /studio/external-dependencies/fonts/bootstrap-icons.woff2?524846017b983fc8ded9325d94ed40f3 HTTP/1.1" 304 -
192.168.3.1 - - [11/Jan/2023:06:38:50 +0000] "GET /studio/external-dependencies/fonts/bootstrap-icons.woff2?524846017b983fc8ded9325d94ed40f3 HTTP/1.1" 304 -
192.168.3.1 - - [11/Jan/2023:06:38:50 +0000] "GET /studio/external-dependencies/fonts/bootstrap-icons.woff2?524846017b983fc8ded9325d94ed40f3 HTTP/1.1" 304 - "http://172.20.69.53/studio/external-dependencies/bootstrap-icons.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.76"

127.0.0.1 - - [11/Jan/2023:06:39:14 +0000] "GET / HTTP/1.1" 200 17574
127.0.0.1 - - [11/Jan/2023:06:39:14 +0000] "GET / HTTP/1.1" 200 17574
127.0.0.1 - - [11/Jan/2023:06:39:14 +0000] "GET / HTTP/1.1" 200 17574
127.0.0.1 - - [11/Jan/2023:06:39:14 +0000] "GET / HTTP/1.1" 200 17574 "-" "Wget"
[Wed Jan 11 06:39:42.599861 2023] [reqtimeout:info] [pid 317] [client 192.168.3.1:60636] AH01382: Request header read timeout
192.168.3.1 - - [11/Jan/2023:06:39:42 +0000] "-" 408 -
192.168.3.1 - - [11/Jan/2023:06:39:42 +0000] "-" 408 -
192.168.3.1 - - [11/Jan/2023:06:39:42 +0000] "-" 408 -
192.168.3.1 - - [11/Jan/2023:06:39:42 +0000] "-" 408 - "-" "-"
127.0.0.1 - - [11/Jan/2023:06:39:44 +0000] "GET / HTTP/1.1" 200 17574
127.0.0.1 - - [11/Jan/2023:06:39:44 +0000] "GET / HTTP/1.1" 200 17574
127.0.0.1 - - [11/Jan/2023:06:39:44 +0000] "GET / HTTP/1.1" 200 17574
127.0.0.1 - - [11/Jan/2023:06:39:44 +0000] "GET / HTTP/1.1" 200 17574 "-" "Wget"
127.0.0.1 - - [11/Jan/2023:06:40:15 +0000] "GET / HTTP/1.1" 200 17574
127.0.0.1 - - [11/Jan/2023:06:40:15 +0000] "GET / HTTP/1.1" 200 17574
127.0.0.1 - - [11/Jan/2023:06:40:15 +0000] "GET / HTTP/1.1" 200 17574
127.0.0.1 - - [11/Jan/2023:06:40:15 +0000] "GET / HTTP/1.1" 200 17574 "-" "Wget"
[Wed Jan 11 06:40:40.543346 2023] [reqtimeout:info] [pid 31] [client 192.168.3.1:60664] AH01382: Request header read timeout
[Wed Jan 11 06:40:40.543343 2023] [reqtimeout:info] [pid 30] [client 192.168.3.1:60663] AH01382: Request header read timeout
192.168.3.1 - - [11/Jan/2023:06:40:40 +0000] "-" 408 -
192.168.3.1 - - [11/Jan/2023:06:40:40 +0000] "-" 408 -
192.168.3.1 - - [11/Jan/2023:06:40:40 +0000] "-" 408 -
192.168.3.1 - - [11/Jan/2023:06:40:40 +0000] "-" 408 -
192.168.3.1 - - [11/Jan/2023:06:40:40 +0000] "-" 408 -
192.168.3.1 - - [11/Jan/2023:06:40:40 +0000] "-" 408 -
192.168.3.1 - - [11/Jan/2023:06:40:40 +0000] "-" 408 - "-" "-"
192.168.3.1 - - [11/Jan/2023:06:40:40 +0000] "-" 408 - "-" "-"
127.0.0.1 - - [11/Jan/2023:06:40:46 +0000] "GET / HTTP/1.1" 200 17574
127.0.0.1 - - [11/Jan/2023:06:40:46 +0000] "GET / HTTP/1.1" 200 17574
127.0.0.1 - - [11/Jan/2023:06:40:46 +0000] "GET / HTTP/1.1" 200 17574
127.0.0.1 - - [11/Jan/2023:06:40:46 +0000] "GET / HTTP/1.1" 200 17574 "-" "Wget"

**Comment by JulianPrieber** [comment]
Please take a look at the recommended NGINX reverse proxy setup: https://github.com/JulianPrieber/llc-docker#nginx

```
listen        443 ssl;
listen        [::]:443 ssl;
listen        80;
listen        [::]:80;
server_name   your.domain.name;


location / {
# Replace with the IP address and port number of your Docker container.
proxy_pass                          [https://127.0.0.1:443](https://127.0.0.1/);
proxy_set_header Host               $host;
proxy_set_header X-Real-IP          $remote_addr;


proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto  https;
proxy_set_header X-VerifiedViaNginx yes;
proxy_read_timeout                  60;
proxy_connect_timeout               60;
proxy_redirect                      off;

# Specific for websockets: force the use of HTTP/1.1 and set the Upgrade header
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection 'upgrade';
proxy_cache_bypass $http_upgrade;
proxy_set_header X-Forwarded-Proto $scheme;

# Fixes Mixed Content errors.
add_header 'Content-Security-Policy' 'upgrade-insecure-requests';

}
}
```

**Comment by dozod-c** [comment]
I'm getting the same issue with a fresh install.  Can't add any links.  Just says "Loading".

I'm setting this error in the Logs when I try go to the links page to add new links:

[Fri Jan 20 09:20:01.349502 2023] [httpd.conf] 172.19.0.4 - - "HEAD /.env HTTP/1.1" 403 - "-" "-" 405 138
[Fri Jan 20 09:20:01.505983 2023] [access_compat:error] [pid 48] [client 172.19.0.4:56638] AH01797: client denied by server configuration: /htdocs/database/database.sqlite
[Fri Jan 20 09:20:01.505844 2023] [httpd.conf] 172.19.0.4 - - "HEAD /database/database.sqlite HTTP/1.1" 403 - "-" "-" 428 138

Using Traefik to reverse proxy. Do you have any tips that will work with Traefik? Here's my docker compose:

version: "3"
services:
  APPNAME:
    restart: unless-stopped
    container_name: littlelink-custom
    image: julianprieber/littlelink-custom
    hostname: littlelink-custom
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/Los_Angeles
      - SERVER_ADMIN=your@email.com
      - HTTP_SERVER_NAME=yourdomain.com
      - HTTPS_SERVER_NAME=yourdomain.com
      - PHP_MEMORY_LIMIT=256M
      - UPLOAD_MAX_FILESIZE=8M
    networks:
      - saltbox
    labels:
      traefik.enable: true
      traefik.http.routers.littlelink-custom-http.entrypoints: web
      traefik.http.routers.littlelink-custom-http.middlewares: globalHeaders@file,redirect-to-https,gzip
      traefik.http.routers.littlelink-custom-http.rule: Host(`yourdomain.com`)
      traefik.http.routers.littlelink-custom-http.service: littlelink-custom
      traefik.http.routers.littlelink-custom.entrypoints: websecure
      traefik.http.routers.littlelink-custom.middlewares: globalHeaders@file,secureHeaders@file
      traefik.http.routers.littlelink-custom.rule: Host(`yourdomain.com`)
      traefik.http.routers.littlelink-custom.service: littlelink-custom
      traefik.http.routers.littlelink-custom.tls.certresolver: cfdns
      traefik.http.routers.littlelink-custom.tls.options: securetls@file
      traefik.http.services.littlelink-custom.loadbalancer.server.port: 80
    volumes:
      - llc:/htdocs
      - /etc/localtime:/etc/localtime:ro
networks:
  saltbox:
    external: true
volumes:
  llc:
    external: true

**Comment by JulianPrieber** [comment]
For the record. Turning on force HTTPS in the config should fix this.
