### ISSUE TITLE
mounting docker volume prevents htdocs folder from being filled, i think i know why

### ISSUE THREAD

**Issue by joshaconnor** [LinkStackOrg/linkstack-docker#44]
Platform: `Ubuntu 22.04 LTS`
Server type: `Docker`

When installing a docker container for littlelink-custom, the container will only run if there is no mounted volume. If there is a mounted volume, the files in the attached folder are not created even if they do not already exist. 

Steps taken: 
1. create container with no volume to test (functions)
2. create container with just files mounted that i wanted to change later, ie. img and theme folder etc. (fails)
3. create container with entire htdocs mounted (failed)

here is where i began to investigate deeper. after creating unmounted and mounted systems, i exec'd into them both and saw that htdocs was populated in the functional unmounted system, but not in the mounted one. attempting to copy files from the unmounted system to the mounted one resulted in an 'unable to edit, permissions' error on the database and log files. 

conclusion?: i think there is an issue with the permissions on the creation step, but the docker compose file i am using has virtually identical configurations for other mounted volumes in several other containers, leading me to thing there is something wrong with the docker container image stored in docker hub. 

notes: i did check the permissions for the local folder, its 1000:1000 and has rwx for owner,group and r-x for others, just like my other container mounted folders. i have also looked at other containers and this container from the inside and found that other containers bring in files and reattribute their ownership to something else. for example: plex pulls in my /tv folder, listed as 1000:1000 in my system and transfers ownership to 'abc:abc.' littlelinks pulls them in as 1000:1000 but all other files in the htdocs folder are 'apache:apache.'

i dont know enough to know why this is a problem, but i am pretty sure its got something to do with how docker created/imported the files inside the container and attributed permissions to them. 

im happy to answer questions about what i did further if that helps.

**Comment by negimeister** [comment]
+1 on this, seeing the same behavior. I tried to ensure that the files and directory have the same owner/group of 100/101 as in the no-mount case, but no luck.

Mounting a docker volume (not an external directory) to /htdocs does work though.

**Comment by s4ke** [comment]
This might be helpful to you. For the swarm setup where we obviously had to use volumes, we opted for a custom startup script that mounted a volume and used symlinks for setting up everything.

https://github.com/JulianPrieber/llc-docker/blob/main/contrib/swarm-deploy/littlelink.yml#L9

Haven't checked this on recent releases, but this should get you started.

**Comment by lephtHanded** [comment]
Yeah, @joshaconnor  - banging my head against the wall as well.
Here's what I did.
1. start the container fresh with no volumes mapped, a new instance.
2. perform the initial startup steps (setting db, admin username/pass, etc...)
3. i then went in and just changed my theme from something other than the defualt.
4. go to **config** > **take backup**  and download the zip - this copies the whole _htdocs_ folder 
5. i destroyed that container, copied the contents of the zip file contents into a folder on the system
6. added a volume mount in the compose file and started the container - got errors about permissions
7. i stopped the container and ``chmod -r 777`` that folder (didn't want to go down the rabbit hole of testing different permissions) and restarted the container - everything works

(if you don't use private browser, you may need to clean your cookies to get back to the admin interface)

**Comment by Nezteb** [comment]
I also have this issue. I'm deploying to [Fly.io](https://fly.io/), but if I include any [volumes/mounts](https://fly.io/docs/reference/volumes/) the app refuses to start because it can't find various files.

**Comment by jerydfans** [comment]
I dont know how to help, just that I am getting the same problem. I am mounting the volume, but nothing is getting written to it.

**Comment by faceslog** [comment]
Same issue there just mounted the htdocs to a directory and nothing happened ....

**Comment by JulianPrieber** [comment]
Please leave a detailed description how you encountered this issue here: https://github.com/LinkStackOrg/linkstack-docker/discussions/64
