### ISSUE TITLE
Mirror container elsewhere than Docker Hub

### ISSUE THREAD

**Issue by samip5** [LinkStackOrg/linkstack-docker#60]
Docker Hub has very restrictive pull limits even authenticated, so please consider also pushing to alternatives like GHCR.

More information: https://docs.docker.com/docker-hub/download-rate-limit/

**Comment by JulianPrieber** [comment]
I'm aware of the rate limit on docker hub, but it has never been an issue so far.
What are you doing to run into the rate limit?

**Comment by samip5** [comment]
> I'm aware of the rate limit on docker hub, but it has never been an issue so far. What are you doing to run into the rate limit?

I'm hosting 200+ containers at home which means that you can hit it pretty quickly whilist updating them. :)

**Comment by JulianPrieber** [comment]
https://github.com/linkstackorg/linkstack-docker/pkgs/container/linkstack

`docker pull ghcr.io/linkstackorg/linkstack`

**Comment by samip5** [comment]
If I'm looking it right, there's no multi-arch manifest as latest tag?

**Comment by JulianPrieber** [comment]
Yeah, my usual script dint really work, so it's individual tags and only amd64 is currently maintained.

**Comment by nikurasutan** [comment]
> > I'm aware of the rate limit on docker hub, but it has never been an issue so far. What are you doing to run into the rate limit?
> 
> I'm hosting 200+ containers at home (Kubernetes cluster) which means that you can hit it pretty quickly whilist updating them. :)

At work we worked arround that by building a simple application that mirrores the needed containers on demand, so only the first pull that our mirror server does counts in the docker hub rate limit.
