### ISSUE TITLE
Unable to add blocks

### ISSUE THREAD

**Issue by untraceablez** [LinkStackOrg/linkstack-docker#65]
https://github.com/LinkStackOrg/linkstack-docker/assets/2263090/913173e6-282f-47fc-8721-27dd7da1a94a

## Issue
The clip above demonstrates the issue better than words. When I go to add a link, I'm stuck perpetually loading on the Add Block screen. Even if I select a block, it just keeps loading indefinitely and I'm unable to fill in any info. 

## Setup 
* **OS:** Unraid 6.11.5
* **Container Version:** linkstackorg/linkstack:unraid (I think it's v4.0.0)
* **Database:** mySQL, running on same Docker network.

**Comment by JulianPrieber** [comment]
Try to turn on force HTTPS in your config.


This issue has been covered here multiple times.

We recommend using HTTPS in your revere proxy or things will break if you don't redirect links to HTTPS

![chrome_7d2b06V6BR](https://github.com/LinkStackOrg/linkstack-docker/assets/60265788/a246a75d-aa53-4a18-a866-401c3d9734c8)

**Comment by Igcorreia** [comment]
For me solved my activating the force HTTPS :)
