### ISSUE TITLE
Can't create links.

### ISSUE THREAD

**Issue by Igcorreia** [LinkStackOrg/linkstack-docker#69]
Platform: `Ubuntu 22.04 LTS`
Server type: `NGINX/Apache2`
PHP version: `8.1`

After a fresh install, I am seeing this error: I can't create Links.
![image](https://github.com/LinkStackOrg/LinkStack/assets/1076409/5027a260-b79f-4060-9559-12c7707db430)

The platform is trying to load a HTTP on a HTTPS site.

**Comment by JulianPrieber** [comment]
https://github.com/LinkStackOrg/linkstack-docker/issues/65

**Comment by Igcorreia** [comment]
For me solved my activating the force HTTPS :)
