### ISSUE TITLE
Linkstack login page issue

### ISSUE THREAD

**Issue by markdudov** [LinkStackOrg/linkstack-docker#74]
Hello! I have a very strange problem. When I open the login page - for example test.com/login instead of prompting me to enter my details it takes me to the home page - test.com     If I open an incognito window and enter the URL test.com/login (the URL is an example, not the actual one) it opens a login page without any problems. What could be the problem as I have it with every single browser? Is it something from the app or the browsers and how could it be solved? Thanks in advance for your time. And I apologize if I didn't explain it very well.

**Comment by JulianPrieber** [comment]
This is a "feature". Implemented in the predecessor of LinkStack. Please have a look at: https://github.com/orgs/LinkStackOrg/discussions/476
You're describing the default behavior if you're logged in.

Not docker related.
