### ISSUE TITLE
Call to undefined funciton simplexml_import_dom() when retrieving favicon

### ISSUE THREAD

**Issue by FiveVoltLogic** [LinkStackOrg/linkstack-docker#75]
I'm using docker to deploy linkstack, using a sqlite database, no reverse proxy. It's been running well, but when I've gone to add a custom URL and checked the box to display website image over link (I can't remember the exact wording) it throws a 500 server error and I can't edit the links or remove the offender. 

I can use the rest of the site fine, so I got the debug option up and when I access the page it says `Call to undefined funciton simplexml_import_dom()` and hilights line 36 of `storage / framework / views / a1faeb3dd3ffed4fc54853ffa80cc5892b1d4a3c.php.` where it looks like it's trying to retrieve the favicon for the website. The link is to the Meetup website if that's of any use.

I have tried restarting the container, removing it and pulling the image again to restart the container. I created a new profile, logged in and did it again to try to figure out where the issue was. There is no issue if the checkbox remains unchecked.

As I can't get in to delete the link that's caused this, I can't add any links to the profile, remove any, or view the profile. Is there any way to get in and change the option manually?

**Comment by JulianPrieber** [comment]
Do other links produce the same error, or is it just that link if you add it?

**Comment by FiveVoltLogic** [comment]
> Do other links produce the same error, or is it just that link if you add it?

Using the same option I added the same link just without clicking `Show website icon on button` and it worked fine. I've also added facebook and instagram links and clicked and followed them fine. The profile page just doesn't load, even when I go to preview the theme, it shows me the debug page.
![image](https://github.com/LinkStackOrg/linkstack-docker/assets/65986111/ab2d3a3b-de34-42ce-a55f-067c8b70b76a)

The rest of the admin site works fine and I can get to everywhere else, except the "Links" menu item, and previewing or viewing the profile.

**Comment by AlexanderMandera** [comment]
The installation of the package `php82-simplexml` is missing in the Dockerfile,
after installing it manually in the console, it works fine.

**Comment by FiveVoltLogic** [comment]
keeps saying install isn't an apk command

**Comment by JulianPrieber** [comment]
Its apk add instead of install

**Comment by JulianPrieber** [comment]
You are correct, I was able to reproduce this. I'll try to issue a fix shortly.

**Comment by FiveVoltLogic** [comment]
Thank you for your help. I've installed it now, just restarting the container for good measure. And it's working perfectly. Thanks!

**Comment by FiveVoltLogic** [comment]
> Thank you for your help. I've installed it now, just restarting the container for good measure. And it's working perfectly. Thanks!
