### ISSUE TITLE
Page links on footer pages 404 error

### ISSUE THREAD

**Issue by FiveVoltLogic** [LinkStackOrg/linkstack-docker#77]
Hello again! This may sound covoluted so I'll try to outline what I'm doing, and what's happening.
I have activated the footer pages. When I follow them from the home page or a link page they get followed correctly and direct to `/pages/privacy`. for example.

When I follow the same link from the page itself (example.com/pages/privacy in the address bar) then it throws me a 404 error.

I can resolve this by setting a name for the page on the config page - ie. typing "Privacy" in the "Title of privacy link." field and clicking save.

**Comment by JulianPrieber** [comment]
Fixed in the latest beta
