### ISSUE TITLE
Missing DB migration in entrypoint

### ISSUE THREAD

**Issue by thomas-netlor** [LinkStackOrg/linkstack-docker#78]
After update, I have an error (500) and it seem to be a missing column `auth_as`.
Running with an external mariadb.

I think a `php artisan migrate` is missing in `docker-entrypoint.sh` ?

Edit: it seem to be a bad migration from this commit https://github.com/LinkStackOrg/LinkStack/commit/3f62c844061af07435d032a6010f1a052e8b3ed0
The new column isn't add because migration is already execute.

**Comment by JulianPrieber** [comment]
This file is used to add the new entry, so we don't have to run migrations when updating https://github.com/LinkStackOrg/LinkStack/commit/3f62c844061af07435d032a6010f1a052e8b3ed0#diff-94158740b7014d67cdac221a855807de0c3455b3f981b6236a30cb268281fdf7.

Are you using MySQL?

**Comment by thomas-netlor** [comment]
I don't check all the code and mechanism.
I see the repository `database/migrations` so for me if you need to update database scheme, it's necessary to create a new migration file (ex: `add_users_auth_as.php`).

Yes I'm using MySQL.

**Comment by JulianPrieber** [comment]
That is also already done with the same commit https://github.com/LinkStackOrg/LinkStack/commit/3f62c844061af07435d032a6010f1a052e8b3ed0#diff-2ff3b06f86e401f4bc4ba2529584ee9b88945dc885b61cca7ed516f53b593e70

Your issue is likly already known and we issued a patch for it: https://github.com/LinkStackOrg/LinkStack/releases/tag/v4.2.1
Load a backup if possible and update again.

**Comment by thomas-netlor** [comment]
I updated this morning to v4.2.1 and it generate this error.
`docker compose pull && docker compose up -d`

The commit add a new column in an existing migration and this migration is already execute before I update linkstack.
So the migration isn't execute a second time and the column added with this commit isn't applied in the database.
You need to create a separated migration like `2023_03_09_121613_update_columns_to_text_type.php` for `littlelink_description` in `users` table.
Or `resources/views/components/finishing.blade.php` isn't working correctly for MySQL ?

**Comment by JulianPrieber** [comment]
You can only update the app using the internal updater.
