### ISSUE TITLE
htdocs volume not working in the official Docker container.

### ISSUE THREAD

**Issue by Leopere** [LinkStackOrg/linkstack-docker#82]
Platform: Docker
Server type: Docker container
PHP version: whatever's in the container

[//]: # (Please make sure you have read the system requirements at https://llc.ovh/req before submitting your issue.)

i'm having trouble getting the htdocs volume to work correctly in the container.  is there any useful information that I could have in regards to this. it works fine if I don't mount a volume to htdocs .

**Comment by C-Fu** [comment]
Can't remember what I did, but I believe we need to change the permission of your host's htdocs bind folder/docker volume to a particular UID and/or GID.

**Comment by Leopere** [comment]
<img width="523" alt="image" src="https://github.com/LinkStackOrg/linkstack-docker/assets/1068374/3319af59-7964-4670-8a1a-095ca8888e68">
seems to be no better :( but thanks for trying @JakeFrosty

**Comment by Leopere** [comment]
well actually kinda does work but you have to navigate into the htdocs folder I'll probably just have to mess with the paths. I shall report back.

**Comment by Leopere** [comment]
ok that worked! @JakeFrosty thanks heaps I would not have guessed those uid/gid's
