### ISSUE TITLE
Caddy Reverse Proxy Fails

### ISSUE THREAD

**Issue by hazzakins** [LinkStackOrg/linkstack-docker#85]
Hi,

Hoping for a little assistance trying to proxy via Caddy in docker and am having some issues getting the site to load.

After some back and forth config testing I got the initial page to load however there is some serious issues with asset loading.

Thanks in advance

**Comment by JulianPrieber** [comment]
We mention this in our documentation, either use https to access your docker container or force redirect all asset requests to https using headers.

An alternative is using the force https setting in your config. This should resolve your issues.

**Comment by hazzakins** [comment]
Hi Julian

Thanks, I've been trying to do this using the NGINX template provided as part of the documentation however I am still facing issues, it doesn't seem to be mixed content related however will need to take another look, else will fail back to proxying via port 80 instead.

**Comment by JulianPrieber** [comment]
Perhaps you want to take a look at your browser's console to see if there are any errors that give any detail on this.
