### ISSUE TITLE
Can't add new Links

### ISSUE THREAD

**Issue by FuckingToasters** [LinkStackOrg/linkstack-docker#86]
Hello, so after i installed it via docker i tried to add a new link (Home => Add Link) I then noticed, that there were an loading cycle which not stopped loading, i then pressed on the cancel , submit button after which i constantly get following errror:
![image](https://github.com/LinkStackOrg/linkstack-docker/assets/94435104/19066397-d309-4e4f-b972-d62f267a618f)

The error from thwe screenshot above not only happen in Home => Add Links but also in Personalization => Links

**Comment by JulianPrieber** [comment]
https://github.com/LinkStackOrg/LinkStack/issues/573

**Comment by JulianPrieber** [comment]
Just to be clear, the error is not the problem here, it's the loading cycle

**Comment by FuckingToasters** [comment]
> Just to be clear, the error is not the problem here, it's the loading cycle

well i fixed the loading cyble by enabeling force redirect to https but this did not solve the error from the screenshot

**Comment by JulianPrieber** [comment]
Sooo the form loads now?

**Comment by FuckingToasters** [comment]
meaning i can add links but not view added links, edit them or remove them

**Comment by JulianPrieber** [comment]
You need to remove the corrupted link from the database to continue to use that user account
