### ISSUE TITLE
Unwanted Redirection

### ISSUE THREAD

**Issue by FuckingToasters** [LinkStackOrg/linkstack-docker#93]
Hello, so i have https://stackzilla.vbucksgenerator.zip i now wanted to add something to the main domain via nginx proxy manager (redirect to anohter domain) but for some reason, the main domain always redirect to the stackzilla subdomain and i don't know, how i can avoid that.

**Comment by JulianPrieber** [comment]
That's not an issue with LinkStack. You may be able to find some help on our community Discord.
You may have to Google some of the details for your NGINX vhost setup.
This shouldn't be too bad to troubleshoot.
