### ISSUE TITLE
Error while Update

### ISSUE THREAD

**Issue by cardi-m** [LinkStackOrg/linkstack-docker#96]
I run LinkStak 4.3.2 over the Docker Container. I Tried to Update it over the Website to 4.3.0, bit get an error. Here is the log:

`Fatal error: Maximum execution time of 30+2 seconds exceeded (terminated) in /htdocs/vendor/spatie/laravel-backup/src/Tasks/Backup/Zip.php on line 87`

any Idea anybody?

**Comment by JulianPrieber** [comment]
Disable backups in your config and try again.
You can also increase the execution time in your php.ini.
