### ISSUE TITLE
Unable to add links

### ISSUE THREAD

**Issue by cancel-cloud** [LinkStackOrg/linkstack-docker#99]
If I try to click add link, the correct page shows up, but stays in the following seen state indefinitely.
![Screenshot 10 11 2023 at 08-05-25@2x](https://github.com/LinkStackOrg/linkstack-docker/assets/76657167/ffa01482-03f6-4183-ac29-ec0d59a6fcaa)

Even after docker container reboot.

Here is the log file, if that helps out
[c6kccof447x2xxq9er97oub1k_logs.txt](https://github.com/LinkStackOrg/linkstack-docker/files/13316574/c6kccof447x2xxq9er97oub1k_logs.txt)

**Comment by lastsamurai26** [comment]
check the .env file and set force_https -> to true
